name: Terraform Destroy
on:
 workflow_dispatch:


jobs:
  destroy:
    name: destroy
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VERSION: 'latest'

    defaults:
      run:
        shell: bash
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Sed
        id: sed
        run: |
          sed -i "s|##ARM_SUBSCRIPTION_ID##|$ARM_SUBSCRIPTION_ID|g" common_config.json
          sed -i "s|##ARM_TENANT_ID##|$ARM_TENANT_ID|g" common_config.json
          sed -i "s|##ARM_CLIENT_ID##|$ARM_CLIENT_ID|g" common_config.json
          sed -i "s|##ARM_CLIENT_SECRET##|$ARM_CLIENT_SECRET|g" common_config.json
          cat common_config.json
          env   
        
      - name: Terraform Init
        id: init
        run: terraform init 
        
      - name: Show Destroy plan
        run: terraform plan -destroy -var-file="common_config.json" -lock=false
        continue-on-error: true

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -var-file="common_config.json" -auto-approve
